name: Release PR

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: itamm15/release-please@1fc1838dea09ad12283726552094d7de37b0e5e0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: develop
          title: "Release: develop -> main"
