name: Release PR

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: itamm15/release-please-action@d25405c9358289d3264fc13d4cd8d527cc9e53ff
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: develop
          title: "Release: develop -> main"
